version: '3'
services:
  redis:
    image: redis
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: '${S3_ACCESS_KEY}'
      MINIO_SECRET_KEY: '${S3_SECRET_KEY}'
    volumes:
      - miniodata:/data
    ports:
      - '1338:9000'
    command: server /data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
  db:
    image: mongo
    env_file: .env
    volumes:
      - dbdata:/data/db
  server:
    build: .
    env_file: .env
    ports:
      - '1337:1337'
    depends_on:
      - db
      - minio
      - redis
volumes:
  dbdata: {}
  miniodata: {}
