version: '3'
services:
  db:
    image: mongo
    env_file: .env
    volumes:
      - dbdata:/data/db
  server:
    build: .
    env_file: .env
    ports:
      - "1337:1337"
    depends_on:
      - db
volumes:
    dbdata: {}
